apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: andylee1973/python:2022-01-22
        name: flaskdemo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: flaskdemo
  labels:
    app: flaskdemo
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32500
  selector:
    app: flaskdemo
